# Generated by Django 4.0.3 on 2026-02-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo_factura', models.CharField(blank=True, max_length=1, null=True)),
                ('activa', models.BooleanField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social_afip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='CotizacionesDolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo_anio', models.IntegerField()),
                ('periodo_mes', models.IntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'cotizaciones_dolar',
                'unique_together': {('periodo_anio', 'periodo_mes')},
            },
        ),
        migrations.CreateModel(
            name='ComprobantesComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comprobante', models.DateField()),
                ('periodo_anio', models.IntegerField()),
                ('periodo_mes', models.IntegerField()),
                ('tipo_comprobante', models.CharField(max_length=20)),
                ('tipo_factura', models.CharField(max_length=1)),
                ('numero_comprobante', models.CharField(max_length=20)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('no_gravado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comisiones.aseguradoras')),
            ],
            options={
                'db_table': 'comprobantes_comisiones',
                'unique_together': {('aseguradora', 'tipo_comprobante', 'tipo_factura', 'numero_comprobante', 'periodo_anio', 'periodo_mes')},
            },
        ),
        migrations.CreateModel(
            name='CobranzasComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('tipo_factura', models.CharField(blank=True, max_length=1, null=True)),
                ('numero_comprobante', models.IntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comisiones.comprobantescomisiones')),
            ],
            options={
                'db_table': 'cobranzas_comisiones',
            },
        ),
    ]
