# Generated by Django 4.0.3 on 2026-02-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Parametro del sistema',
                'verbose_name_plural': 'Parametros del sistema',
                'db_table': 'parametros_sistema',
            },
        ),
    ]
