# Generated by Django 4.0.3 on 2026-02-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_parametrosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoras',
            name='color',
            field=models.CharField(default='#3366cc', max_length=7),
        ),
    ]
