# Generated by Django 4.0.3 on 2026-03-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0003_aseguradoras_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoras',
            name='grupo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
