# Generated by Django 4.0.3 on 2026-03-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0004_aseguradoras_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('ramo', models.CharField(blank=True, max_length=100, null=True)),
                ('poliza', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('premio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prima', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('comision_compania', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comision_adelantada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comision_agente', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comision_agente_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comision_agente_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cotizacion_dolar', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('meses_adelanto', models.IntegerField(blank=True, null=True)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.aseguradoras')),
            ],
        ),
    ]
