# Generated by Django 4.0.3 on 2026-03-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0005_liquidacionaseguradora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('registros', models.IntegerField(default=0)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.aseguradoras')),
            ],
        ),
        migrations.AddField(
            model_name='liquidacionaseguradora',
            name='importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='comisiones.importacioncomisiones'),
        ),
    ]
