# Generated by Django 4.0.3 on 2026-03-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0006_importacioncomisiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacioncomisiones',
            name='cantidad_clientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncomisiones',
            name='comision_total',
            field=models.FloatField(default=0),
        ),
    ]
