# Generated by Django 4.0.3 on 2026-03-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0007_importacioncomisiones_cantidad_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionaseguradora',
            name='quincena',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
