# Generated by Django 4.0.3 on 2026-03-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0008_liquidacionaseguradora_quincena'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionaseguradora',
            name='endoso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
