# Generated by Django 4.0.3 on 2026-03-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0009_liquidacionaseguradora_endoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionaseguradora',
            name='descuento_adelanto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
