# Generated by Django 4.0.3 on 2026-03-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0010_liquidacionaseguradora_descuento_adelanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAS',
            fields=[
                ('codigo_pas', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('cvu', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pas',
            },
        ),
        migrations.CreateModel(
            name='PASCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=200)),
                ('cliente_clave', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('pas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.pas')),
            ],
            options={
                'db_table': 'pas_clientes',
            },
        ),
        migrations.CreateModel(
            name='PASAseguradora',
            fields=[
                ('codigo_pas_aseguradora', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField()),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.aseguradoras')),
                ('pas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.pas')),
            ],
            options={
                'db_table': 'pas_aseguradoras',
            },
        ),
    ]
