# Generated by Django 4.0.3 on 2026-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0011_pas_pascliente_pasaseguradora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pascliente',
            name='cliente_clave',
        ),
        migrations.AddField(
            model_name='pascliente',
            name='cliente_clave1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pascliente',
            name='cliente_clave2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
