# Generated by Django 4.0.3 on 2026-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0012_remove_pascliente_cliente_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pas',
            name='activo',
        ),
        migrations.AlterField(
            model_name='pas',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pas',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
