# Generated by Django 4.0.3 on 2026-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0013_remove_pas_activo_alter_pas_cuit_alter_pas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaseguradora',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
