# Generated by Django 4.0.3 on 2026-03-16 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0014_alter_pasaseguradora_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('anio_poliza', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.aseguradoras')),
            ],
        ),
    ]
