# Generated by Django 4.0.3 on 2026-03-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0015_reglacomision'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reglacomision',
            table='reglas_comision',
        ),
    ]
