# Generated by Django 4.0.3 on 2026-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0016_alter_reglacomision_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacomision',
            name='rango',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reglacomision',
            name='tope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterModelTable(
            name='reglacomision',
            table=None,
        ),
    ]
