# Generated by Django 4.0.3 on 2026-03-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0017_reglacomision_rango_reglacomision_tope_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reglacomision',
            table='reglas_comision',
        ),
    ]
