# Generated by Django 4.0.3 on 2026-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0018_alter_reglacomision_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasaseguradora',
            name='porcentaje_comision',
        ),
        migrations.AddField(
            model_name='pasaseguradora',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasaseguradora',
            name='rango',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
