# Generated by Django 4.0.3 on 2026-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0019_remove_pasaseguradora_porcentaje_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacomision',
            name='base_comision',
            field=models.CharField(choices=[('Prima', 'Prima'), ('Comision', 'Comisión Agente')], default='Prima', max_length=10),
        ),
    ]
