# Generated by Django 4.0.3 on 2026-03-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0020_reglacomision_base_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoras',
            name='incluye_iva',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
