# Generated by Django 4.0.3 on 2026-03-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0021_aseguradoras_incluye_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pascliente',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comisiones.aseguradoras'),
        ),
    ]
