# Generated by Django 4.0.3 on 2026-04-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0022_pascliente_aseguradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionaseguradora',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
