# Generated by Django 4.0.3 on 2026-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0023_alter_liquidacionaseguradora_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoras',
            name='invierte_signo',
            field=models.BooleanField(default=False),
        ),
    ]
